server:
  port: 7833

logging:
  level:
    soya.framework: DEBUG

spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: absitdsdevwusseddw001
          account-key: yYF0293O1dHvHwfwKektJa3ptAMgH219Pp7886kyqQ/1EHivjCL4L9Dy+W/mx1JyjM+BEVqHC3xvSKkzKrbz7g==
          endpoint: https://absitdsdevwusseddw001.blob.core.windows.net

workspace:
  home: C:/Albertsons/workspace


soya:
  framework:
    scanPackages: org.springframework